# Generated by Django 4.1.5 on 2023-05-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('deposit', models.CharField(max_length=25)),
                ('memo', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.FloatField(default=10000.0),
        ),
    ]
