# Generated by Django 4.1.5 on 2023-05-14 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_rename_deposit_transaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='Transaction_type',
            new_name='transaction_type',
        ),
    ]
